### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Arniiiii**

### CODE REVIEW

**Comment by MrPenguin07** [comment]
Hey Gerodote,

Appreciate the PR. Guess there are a few using my ebuilds after all :)
The readme changes are helpful thanks.

Regarding the changes to `next export`, funnily enough we were kinda discussing this yesterday [here in the upscayl repo](https://github.com/upscayl/upscayl/commit/b2a3e54dfc374b674a4fe52664e0c4be80b27f9d#commitcomment-142087995)!

As for patching `package.json`, I think it's best to first see what NayamAmarshe means by ["No worries, I'll fix it"](https://github.com/upscayl/upscayl/commit/b2a3e54dfc374b674a4fe52664e0c4be80b27f9d#commitcomment-142097698) as upstream should quickly take care of this for us.

I have considered patching the package.json to build this package 'the gentoo way'... when creating this ebuild I seem to recall being forced to run at least one of the package build scripts to get the raw files.

At present we build the dist:deb and pluck the compiled binary and files+dir structure from it (this is a lazy method as the CI/CD github action creates the proper dir structure and makes the src_install() section far,far simpler).
Not exactly how I prefer to do it, but it does work fine I guess. 

May rethink the entire ebuild.

**Review by MrPenguin07 — DISMISSED** [review]

**Comment by Arniiiii** [comment]
@MrPenguin07  

Thanks for quick response.

So, regarding the patch, what you propose to do right now?

**Comment by MrPenguin07** [comment]
> @MrPenguin07
> 
> Thanks for quick response.
> 
> So, regarding the patch, what you propose to do right now?

To resolve the current build problem, perhaps sending this PR to next.config.js and package.json upstream to upscayl repo would be welcomed.

I'm not sure if it's the solution they have in mind however one way or another an upstream fix is the proper fix :)

**Comment by Arniiiii** [comment]
@MrPenguin07 
You can now merge just README

**Review by MrPenguin07 — APPROVED** [review]
Thanks!

**Pull request merged**
